apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "intelligent-vms.fullname" . }}-config
  labels:
    {{- include "intelligent-vms.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.commonConfig }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
