{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "intelligent-vms.fullname" . }}
  labels:
    {{- include "intelligent-vms.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "intelligent-vms.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "intelligent-vms.name" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.networkPolicy.extraIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "intelligent-vms.name" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.dns.namespace | quote }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.dns.podLabels | nindent 14 }}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- with .Values.networkPolicy.extraEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
