#!/usr/bin/env python3
"""Generate and verify Phase-9 backup/DR evidence without making production claims."""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SCHEMA_VERSION = "phase9-dr-evidence-v1"
EXERCISE_QUALIFICATION = (
    "EXERCISE_EVIDENCE_ONLY_NOT_A_PRODUCTION_RPO_RTO_GUARANTEE"
)


def _parse_time(value: str) -> datetime:
    parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    if parsed.tzinfo is None:
        raise ValueError("timestamps must include a timezone")
    return parsed.astimezone(timezone.utc)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def build_manifest(
    root: Path,
    *,
    generated_at: datetime | None = None,
) -> dict[str, Any]:
    """Build a checksum manifest for one backup set.

    Args:
        root: Backup-set directory to inventory recursively.
        generated_at: Optional timezone-aware manifest timestamp for deterministic use.

    Returns:
        Manifest dictionary containing relative paths, byte sizes and SHA-256 hashes.

    Raises:
        ValueError: If the root is not a directory, a symlink is encountered, or
            generated_at is timezone-naive.
        OSError: If backup files cannot be read.
    """
    root = root.resolve()
    if not root.is_dir():
        raise ValueError("backup root must be an existing directory")

    stamp = generated_at or datetime.now(timezone.utc)
    if stamp.tzinfo is None:
        raise ValueError("generated_at must be timezone-aware")

    files: list[dict[str, Any]] = []
    for path in sorted(root.rglob("*")):
        if path.is_symlink():
            raise ValueError(f"backup manifest refuses symlink: {path}")
        if not path.is_file():
            continue
        relative = path.relative_to(root).as_posix()
        files.append(
            {
                "path": relative,
                "bytes": path.stat().st_size,
                "sha256": _sha256(path),
            }
        )

    return {
        "schema_version": SCHEMA_VERSION,
        "kind": "backup_manifest",
        "generated_at": stamp.astimezone(timezone.utc).isoformat(),
        "root_name": root.name,
        "files": files,
    }


def verify_manifest(manifest_path: Path, root: Path) -> list[str]:
    """Verify a backup directory exactly against a Phase-9 checksum manifest.

    Args:
        manifest_path: JSON manifest generated by :func:`build_manifest`.
        root: Backup-set directory whose files must match the manifest.

    Returns:
        List of missing, unexpected, size or SHA-256 verification errors. An empty
        list means the directory matches the manifest exactly.

    Raises:
        ValueError: If the manifest schema is unsupported, an unsafe path is
            present, or the backup directory contains symlinks.
        OSError: If the manifest or backup files cannot be read.
        json.JSONDecodeError: If the manifest is not valid JSON.
    """
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("schema_version") != SCHEMA_VERSION:
        raise ValueError("unsupported DR evidence schema")
    if manifest.get("kind") != "backup_manifest":
        raise ValueError("manifest kind must be backup_manifest")

    root = root.resolve()
    if not root.is_dir():
        raise ValueError("backup root must be an existing directory")

    expected_paths: set[str] = set()
    errors: list[str] = []
    for item in manifest.get("files", []):
        if not isinstance(item, dict):
            raise ValueError("manifest files must contain objects")
        raw = str(item.get("path", ""))
        relative = Path(raw)
        if not raw or relative.is_absolute() or ".." in relative.parts:
            raise ValueError(f"unsafe manifest path: {raw!r}")
        expected_paths.add(relative.as_posix())
        path = root / relative
        if path.is_symlink():
            raise ValueError(f"backup verification refuses symlink: {path}")
        resolved = path.resolve()
        if root not in resolved.parents and resolved != root:
            raise ValueError(f"manifest path escapes backup root: {raw!r}")
        if not resolved.is_file():
            errors.append(f"missing:{raw}")
            continue
        actual_size = resolved.stat().st_size
        if actual_size != int(item.get("bytes", -1)):
            errors.append(f"size:{raw}")
            continue
        if _sha256(resolved) != str(item.get("sha256", "")):
            errors.append(f"sha256:{raw}")

    actual_paths: set[str] = set()
    for path in sorted(root.rglob("*")):
        if path.is_symlink():
            raise ValueError(f"backup verification refuses symlink: {path}")
        if path.is_file():
            actual_paths.add(path.relative_to(root).as_posix())

    for extra in sorted(actual_paths - expected_paths):
        errors.append(f"unexpected:{extra}")

    return errors

def build_exercise_evidence(
    *,
    exercise_id: str,
    exercise_type: str,
    failure_at: str,
    service_restored_at: str,
    restore_point_at: str,
    validation: str,
    target_rpo_seconds: float | None = None,
    target_rto_seconds: float | None = None,
    notes: str = "",
) -> dict[str, Any]:
    """Build measured RPO/RTO evidence for one controlled recovery exercise.

    Args:
        exercise_id: Operator-defined unique exercise identifier.
        exercise_type: Exercise category such as restore, region-loss or upgrade-rollback.
        failure_at: Simulated/actual failure instant with timezone.
        service_restored_at: Instant the operator declared service restored.
        restore_point_at: Latest restorable data instant used by the exercise.
        validation: Operator validation result: pass, fail or pending.
        target_rpo_seconds: Optional exercise RPO objective.
        target_rto_seconds: Optional exercise RTO objective.
        notes: Optional bounded operator notes.

    Returns:
        Evidence dictionary containing measured RPO/RTO and target comparisons.

    Raises:
        ValueError: If inputs/timestamps are invalid or temporally inconsistent.
    """
    if validation not in {"pass", "fail", "pending"}:
        raise ValueError("validation must be pass, fail or pending")
    if not exercise_id.strip() or not exercise_type.strip():
        raise ValueError("exercise_id and exercise_type are required")
    if target_rpo_seconds is not None and target_rpo_seconds < 0:
        raise ValueError("target_rpo_seconds must be non-negative")
    if target_rto_seconds is not None and target_rto_seconds < 0:
        raise ValueError("target_rto_seconds must be non-negative")

    failure = _parse_time(failure_at)
    restored = _parse_time(service_restored_at)
    restore_point = _parse_time(restore_point_at)

    if restored < failure:
        raise ValueError("service_restored_at cannot be before failure_at")
    if restore_point > failure:
        raise ValueError("restore_point_at cannot be after failure_at")

    observed_rto = (restored - failure).total_seconds()
    observed_rpo = (failure - restore_point).total_seconds()

    rpo_met = (
        observed_rpo <= target_rpo_seconds
        if target_rpo_seconds is not None
        else None
    )
    rto_met = (
        observed_rto <= target_rto_seconds
        if target_rto_seconds is not None
        else None
    )

    return {
        "schema_version": SCHEMA_VERSION,
        "kind": "dr_exercise",
        "qualification": EXERCISE_QUALIFICATION,
        "exercise_id": exercise_id.strip(),
        "exercise_type": exercise_type.strip(),
        "validation": validation,
        "failure_at": failure.isoformat(),
        "service_restored_at": restored.isoformat(),
        "restore_point_at": restore_point.isoformat(),
        "observed_rpo_seconds": observed_rpo,
        "observed_rto_seconds": observed_rto,
        "target_rpo_seconds": target_rpo_seconds,
        "target_rto_seconds": target_rto_seconds,
        "rpo_target_met": rpo_met,
        "rto_target_met": rto_met,
        "notes": notes[:4000],
    }


def _write_json(payload: dict[str, Any], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    """Run the Phase-9 backup-manifest or DR-exercise evidence CLI.

    Returns:
        Zero on successful generation/verification, or one for manifest mismatch.
    """
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)

    manifest_parser = sub.add_parser("manifest")
    manifest_parser.add_argument("--root", type=Path, required=True)
    manifest_parser.add_argument("--output", type=Path, required=True)

    verify_parser = sub.add_parser("verify")
    verify_parser.add_argument("--root", type=Path, required=True)
    verify_parser.add_argument("--manifest", type=Path, required=True)

    exercise_parser = sub.add_parser("exercise")
    exercise_parser.add_argument("--exercise-id", required=True)
    exercise_parser.add_argument("--exercise-type", required=True)
    exercise_parser.add_argument("--failure-at", required=True)
    exercise_parser.add_argument("--service-restored-at", required=True)
    exercise_parser.add_argument("--restore-point-at", required=True)
    exercise_parser.add_argument(
        "--validation",
        choices=("pass", "fail", "pending"),
        required=True,
    )
    exercise_parser.add_argument("--target-rpo-seconds", type=float)
    exercise_parser.add_argument("--target-rto-seconds", type=float)
    exercise_parser.add_argument("--notes", default="")
    exercise_parser.add_argument("--output", type=Path, required=True)

    args = parser.parse_args()

    if args.command == "manifest":
        _write_json(build_manifest(args.root), args.output)
        return 0

    if args.command == "verify":
        errors = verify_manifest(args.manifest, args.root)
        if errors:
            for error in errors:
                print(error)
            return 1
        print("backup_manifest_verified")
        return 0

    payload = build_exercise_evidence(
        exercise_id=args.exercise_id,
        exercise_type=args.exercise_type,
        failure_at=args.failure_at,
        service_restored_at=args.service_restored_at,
        restore_point_at=args.restore_point_at,
        validation=args.validation,
        target_rpo_seconds=args.target_rpo_seconds,
        target_rto_seconds=args.target_rto_seconds,
        notes=args.notes,
    )
    _write_json(payload, args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
